export const galleryItems = [
  {
    title: "Festivals",
    category: "Festivals",
    caption: "Placeholder cultural artwork for festival memories. Official event photography is pending source verification.",
    alt: "Non-photographic Bengali cultural placeholder for festivals",
    src: "/images/gallery/festivals-placeholder.svg",
    width: 1200,
    height: 800,
  },
  {
    title: "Performances",
    category: "Performances",
    caption: "Placeholder cultural artwork for music, dance and performance moments.",
    alt: "Non-photographic cultural placeholder with performance motifs",
    src: "/images/gallery/performances-placeholder.svg",
    width: 1200,
    height: 800,
  },
  {
    title: "Community",
    category: "Community",
    caption: "Placeholder cultural artwork for intergenerational community belonging.",
    alt: "Non-photographic cultural placeholder with connected community motifs",
    src: "/images/gallery/community-placeholder.svg",
    width: 1200,
    height: 800,
  },
  {
    title: "Social Impact",
    category: "Social Impact",
    caption: "Placeholder cultural artwork for compassionate and environmental initiatives.",
    alt: "Non-photographic cultural placeholder with hands and leaf motifs",
    src: "/images/gallery/social-impact-placeholder.svg",
    width: 1200,
    height: 800,
  },
  {
    title: "Women of Aarohan",
    category: "Women of Aarohan",
    caption: "Placeholder cultural artwork honoring leadership, creativity and contribution without identifying people from images.",
    alt: "Non-photographic respectful placeholder for Women of Aarohan",
    src: "/images/gallery/women-placeholder.svg",
    width: 1200,
    height: 800,
  },
  {
    title: "Celebrations",
    category: "Celebrations",
    caption: "Placeholder cultural artwork for shared festive celebrations and future source-verified galleries.",
    alt: "Non-photographic Bengali cultural placeholder for celebrations",
    src: "/images/gallery/celebrations-placeholder.svg",
    width: 1200,
    height: 800,
  },
] as const;
